spring:
  application:
    name: wallpaper-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:admin}
    url: ${DB_URL:jdbc:mysql://localhost:3306/wallpaper_db}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

server:
  port: ${APP_PORT:8080}
  error:
    include-message: always
