spring:
  application:
    name: wallpaper-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/wallpaper_db
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

server:
  port: 8080
  error:
    include-message: always
